site_name: Second-Brain-Tools
site_url: https://rohanbatrain.github.io/Second-Brain-Tools/
theme:
  name: material
nav:
    - Home: index.md
    - Config: Config.md
      - .sbt_config: SBT-Config.md
    - Bullet-Journal: Bullet-Journal.md
    - Capture: Capture.md
    - Daily-Note: Daily-Note.md
    - Notes: Notes.md
    - Quick-Capture: Quick-Capture.md
    - Random-Note : Random-Note.md
