name: Codecov

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Codecov integration
      run: |
        pip install codecov
        pip install pytest-cov
        pytest --cov=./ --cov-report=xml
        codecov
    #- name: Codecov
    #  uses: codecov/codecov-action@v3.1.1

    #- name: legacy 
    #  run: bash <(curl -s https://codecov.io/bash)
