name: Codecov

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Codecov
      uses: codecov/codecov-action@v3.1.1

    - name: legacy 
      run: bash <(curl -s https://codecov.io/bash)
